name: update-bus-data

on:
  schedule:
    - cron: '30 2 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout to repo
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.8.3
          
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Refresh bus data
        env:
          LTA_Account_Key: ${{ secrets.LTA_ACCOUNT_KEY }}
        run: python updateBusData.py
        
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Updated bus data"
          git push
